### ISSUE TITLE
SEC-3954 IDOR on /api/SetProfileData - it is possible to set any image (even owned by other organizations) as profile or signature photo (01/12/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#11]
Severity: Medium

In the  request to /api/SetProfileData it is possible to specify file id for profile or signature photo. File might be located in any organization.

**Comment by shaileshtayde** [comment]
@cphillips83 @shivmishra we'd need to implement the permission check _photoid_ and _signature_ in `UpdateCustomFields `function. i.e. for resp. file(s)

**Comment by shivmishra** [comment]
should be fixed here https://github.com/MindMatrix/AMP/pull/48326

**Comment by shivmishra** [comment]
save organization should be tested

**Comment by sunrao** [comment]
@YogeshRevclerx Pl. test this

**Comment by YogeshRevclerx** [comment]
@shivmishra sir, the issue is still there as I am able to change the Profile image and signature image of a user through "/api/SetProfileData" using the image id from a different org.

![image](https://user-images.githubusercontent.com/92095999/160834646-c4af666f-6292-4b95-bb35-60d5e7718915.png)

![image](https://user-images.githubusercontent.com/92095999/160834895-1311721c-f0be-4da5-8c2c-546e496c2a46.png)

**Comment by shivmishra** [comment]
@YogeshRevclerx can u verify again

**Comment by YogeshRevclerx** [comment]
@shivmishra Sir, still not resolved.

**Comment by shivmishra** [comment]
plz verify again

**Comment by YogeshRevclerx** [comment]
@shivmishra Not able to change Profile image and Signature image through API and Manually as well.

**Comment by shivmishra** [comment]
@YogeshRevclerx plz check again

**Comment by YogeshRevclerx** [comment]
@shivmishra Sir, issue is still the same.

**Comment by YogeshRevclerx** [comment]
@shivmishra After the fix, this is working as expected. Please send this PR for Release.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have Verified above Security issue.and its Working Fine and Its move to Resolved now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm this on their end.
