### ISSUE TITLE
#1405008, #1405251 Stored XSS in fields for video content

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#140]
Steps to reproduce: 
Open <URL>/#gallery/videos and copy ID of any video (<VIDEO_ID>)
Set corresponding values instead of <ASPXAUTH_COOKIE>, <X_CSRF_TOKEN> and <VIDEO_ID> and make the following request
> curl https://partners.acronis.com/api/savevideo -i -b ".ASPXAUTH=<ASPXAUTH_COOKIE>" -H "X-Csrf-Token: <X_CSRF_TOKEN>" -H "Content-Type:application/json" -d '{"fileid":<VIDEO_ID>,"name":"\" onload=\"alert(1)","language":0,"description":"","embedlink":"https://google.com/","thumbnail":null,"filters":"","startdate":"","enddate":""}

Open preview for the video and see JavaScript payload from field "name" executed (alert with message "1")
Set corresponding values instead of <ASPXAUTH_COOKIE>, <X_CSRF_TOKEN> and <VIDEO_ID> and make the following request
> curl https://partners.acronis.com/api/savevideo -i -b ".ASPXAUTH=<ASPXAUTH_COOKIE>" -H "X-Csrf-Token: <X_CSRF_TOKEN>" -H "Content-Type:application/json" -d '{"fileid":<VIDEO_ID>,"name":"test","language":0,"description":"","embedlink":"javascript:alert(2)","thumbnail":null,"filters":"","startdate":"","enddate":""}

Open preview for the video and see JavaScript payload from field "embedlink" executed (alert with message "2")

Fix: Encode untrusted input according to the rendering context; Whitelist allowed schemes for links

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue, I am able to execute JS payload on the name filed but when i trying to do the same with embed link filed, JS is not getting execute.
Kindly provide additional info realted to embed filed , so i can reproduce issue on my side.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client for additional details.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx, Acronis has confirmed this is not reproducible for the embed link. However, there is missing HTML encoding for video name and description. As a result, XSS still might be possible. For example, for video description the following payload would work: test\" onmouseover=\"alert(1)\" \"test.

Request example via curl
curl [https://partners.acronis.com/api/savevideo](https://www.google.com/url?q=https://partners.acronis.com/api/savevideo&sa=D&source=docs&ust=1661805198066924&usg=AOvVaw0JqXG0bvt1novbRxUrrDBi) -i -b ".ASPXAUTH=<session>" -H "X-Csrf-Token: <csrf_token>" -H "Content-Type:application/json" --data-binary @data.json

where data.json is a file which contains the following:
{​"fileid":<file_id>,"name":"test", "language":0,"description":"test\" onmouseover=\"alert(1)\" \"test '","embedlink":"[https://videodelivery.net/test](https://www.google.com/url?q=https://videodelivery.net/test&sa=D&source=docs&ust=1661805198067069&usg=AOvVaw1-rrilQLSkrD19eWLtWCZ3)","thumbnail":null,"filters":"","startdate":"","enddate":""}

It is required to set proper values for <session>, <csrf_token>, <file_id>

I've seen that there is some filtering present on backend, which removes "<" if there is a letter afterwords. It is a bad practice since it is easy to miss something, and as a result it might be possible to bypass such filtering. Proper fix is to encode untrusted input (HTML encoding for HTML context, etc., [https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html](https://www.google.com/url?q=https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html&sa=D&source=docs&ust=1661805198067127&usg=AOvVaw1yRvtnTaL8gU8R3g3cw-wi))

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and JS is getting executed by following the above mention steps.
User Name : Puneet Security 
Company Name : Automation Testers

![image](https://user-images.githubusercontent.com/92088937/187637104-2b446c4b-b1af-4f46-a220-bf9a1140cf90.png)

**Comment by shivmishra** [comment]
should be fixed here after build https://github.com/MindMatrix/AMP/pull/52057
@IshantRevclerx plz verify

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52057.dvl.amp.vg/login ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir,  I have checked above issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx Acronis has mentioned the issue is still reproducible using the same steps. Can you verify this again?

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have verifiyed again at my end  on Acronis production using above mentioned steps , the issue is not reproducable now.
kindly provide the additional info or the users that are being used.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx
1. Create a video, add XSS to its name and description
2. Create another video, add XSS to its name and description
3. Add the same filter on both then view a video and hover on the description and name of the video displayed in the related category, it will execute the XSS.


https://user-images.githubusercontent.com/31324885/194923412-1a132dc9-8443-45a3-9147-40609ba216cd.mp4

**Comment by IshantRevclerx** [comment]
@shivmishra sir, I have verified above issue on main, this issue still exist in Releted Video Functinality  
![image](https://user-images.githubusercontent.com/92088937/195007803-b36ae7fc-07b0-4b5a-85e6-9274ae5a4f33.png)

**Comment by shivmishra** [comment]
fixed here https://github.com/MindMatrix/AMP/pull/53058

**Comment by IshantRevclerx** [comment]
As disscussed with shiv sir assignining it back

**Comment by shivmishra** [comment]
check in branch after build

**Comment by IshantRevclerx** [comment]
@sunrao sir, @shivmishra sir, I have checked above security issue on the given branch ( https://pr-53375.dvl.amp.vg/ ) and Its working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on the Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
Client has confirmed the fix.
