### ISSUE TITLE
#1478438 Stored XSS on /#connections/lists page in filters (02/14/2022)

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#29]
Severity: Medium

Stored XSS on /#connections/lists page in filters. Together with IDOR in lists it is possible to inject payload on list page located in other organizations. Steps to reproduce:
Make request to /api/SaveListInfo to change the list. Add the following to the filters: qwerty\" onclick=\"alert(123) 
Open /#connections/lists
Open filters -> click on just added filter
See JS executed

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have Checked above mentioned Issue with normal User and after following the steps mentioned above,JS is not getting ecxecuted. 

User : Security Ishant
Company Name : Automation Tester

![image](https://user-images.githubusercontent.com/92088937/176363262-7f19b85c-d053-4268-a44e-d2468e5a16c6.png)

**Comment by IshantRevclerx** [comment]
@pKanth Sir, I have checked above security issue on the given branch ( https://pr-51754.dvl.amp.vg/ ) and JS is still getting executed.
![image](https://user-images.githubusercontent.com/92088937/186384228-932ed17c-4dc1-4cc5-a4c9-5ea98ac6264a.png)

**Comment by sabhareeraj** [comment]
![image](https://user-images.githubusercontent.com/98084240/186898030-1e22fb0f-0e8f-40dc-a6d2-148cb67e375d.png)
![image](https://user-images.githubusercontent.com/98084240/186898130-29d3af42-2355-4613-9354-4765f1445284.png)

@IshantRevclerx , can you please explain how you produced as i am not able to produce issue.

**Comment by sabhareeraj** [comment]
@IshantRevclerx , issue fixed now. Please test again.

**Comment by IshantRevclerx** [comment]
@sabhareeraj, I have checked above security issue on the given branch ( https://pr-51754.dvl.amp.vg/ ), If I enter  " Onmouseover="confirm(164)" in the filter field and after that on hovering mouse over the filter JS is still getting executed.

![image](https://user-images.githubusercontent.com/92088937/187656997-93a8e564-6415-4e94-8f65-0562e3a97b5e.png)

**Comment by sabhareeraj** [comment]
@IshantRevclerx , removing Js in filter view. Please test again.

**Comment by IshantRevclerx** [comment]
@sabhareeraj , @pKanth Sir, I have checked above security issue on the given branch ( https://pr-51754.dvl.amp.vg/ ), If I enter " Onmouseover="confirm(164)" in the filter field and after that on hovering mouse over the filter JS is still getting executed.

![image](https://user-images.githubusercontent.com/92088937/187916905-eea1ef44-2c6e-4890-8e20-83b676b5ae19.png)

**Comment by sabhareeraj** [comment]
@IshantRevclerx , this issue is not reproducing. can you please explain how you reproduced?

![image](https://user-images.githubusercontent.com/98084240/187922000-450bb7d6-95df-4038-bbd3-29d7d88e025e.png)

**Comment by IshantRevclerx** [comment]
@sabhareeraj, Please find the screen recording of the steps that I am following to repoduce the issue.

https://user-images.githubusercontent.com/92088937/188059549-1ca36964-9c67-446a-aec4-ef1ba099ae58.mp4

**Comment by sabhareeraj** [comment]
@IshantRevclerx , Issue fixed now. Please test again.

**Comment by IshantRevclerx** [comment]
@pKanth Sir, @sabhareeraj, I have checked above security issue on the given branch ( https://pr-51754.dvl.amp.vg/ ) JsS is not getting executed now.
But, if click on filters and select on any filter UI is not showing appropriate as compare to main.
**On branch** : 
![image](https://user-images.githubusercontent.com/92088937/188369952-884f651b-310d-40ef-a72d-cdac24bf623d.png)

**On Main** : 
![image](https://user-images.githubusercontent.com/92088937/188370530-542369b1-2733-48f0-847b-7bf5fcef1925.png)

**Comment by sabhareeraj** [comment]
@IshantRevclerx , label got fixed. Please check now

**Comment by IshantRevclerx** [comment]
@pKanth Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch ( https://pr-51754.dvl.amp.vg/ ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have verified the above issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to verify the same.

**Comment by prashantjadhav92** [comment]
Verified by the client.
