### ISSUE TITLE
SEC-4356 Email change without password confirmation on /api/SaveUser

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#53]
It is possible to change email without password confirmation using API endpoint /api/SaveUser. Using this endpoint it is possible to change email address for users in the same organization (including currently logged in user)

Steps to Reproduce:
* Send POST request to /api/SaveUser with the following body
{"userid":<VICTIM_USER_ID>,"groups":[],"json":{"email":"<ATTACKER_EMAIL>"},"cfjson":{}}

Fix: It should not be possible to change email address without password confirmation

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have Check above mentioned issue. it is possible for normal user to change Email ID of any user for same Organization, even though Email ID field is disabled for normal user 
![Save Email Id -2](https://user-images.githubusercontent.com/92088937/173506665-f9a46475-196d-4443-9a6c-eeeba3315aa5.png)
After Changing the Email address.
![Save User-3](https://user-images.githubusercontent.com/92088937/173506718-5cf24728-9904-431b-a5f8-02ead3363293.png)
as shown in the screenshoot.

**Comment by IshantRevclerx** [comment]
Users: puneet security and security ishant (Both normal users)
Company- Automation Testers

**Comment by shivmishra** [comment]
should be fixed on this https://github.com/MindMatrix/AMP/pull/50389

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, I have Checked above mentioned  Security Issue on the given branch "https://dvl-pr-50389.amp.vg/"  and Its Working fine as expected. 
but  Similar to the Ticket Number #51 User Info Modal not getting closed with Normal User.

User : Security Ishant
Company Name : Automation Tester.

**Comment by shivmishra** [comment]
@IshantRevclerx should be fixed

**Comment by IshantRevclerx** [comment]
@sunrao Sir, I have Checked the functionality of above mentioned Issue and its working as expected.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above mentioned security issue on production and its working fine now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx client has mentioned this is still reproducible on their end. Can you please confirm this again?

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, I tested again and User can not change the email address of other user in the same organization but can change his own email address with /api/SaveUser.
kindly check.
Url : https://mm.amp.vg/
User : Ishant
Company : Automation Test

**Comment by shivmishra** [comment]
@sunrao @IshantRevclerx @shaileshtayde i allowed SiteSuperAdmin user and self user can change email address. :Please let me know if you want to restrict normal user to not change self email then i will remove that condition.

Please confirm.

**Comment by sunrao** [comment]
@shivmishra Only Super/Site Admin can change the User email address.

**Comment by shivmishra** [comment]
@sunrao can i not change my email address?

**Comment by sunrao** [comment]
![image](https://user-images.githubusercontent.com/6465639/180427133-98d298c3-745f-4930-a525-d90c59fa6328.png)

No as the user email is validated on creation

**Comment by shivmishra** [comment]
its ok i will remove extra check to validate but also its validated on edit as well

**Comment by shivmishra** [comment]
fixed in this PR https://github.com/MindMatrix/AMP/pull/51106

**Comment by IshantRevclerx** [comment]
@sunrao and @shivmishra Sir I have Checked above mention security Issue on the given branch ( https://pr-51106.dvl.amp.vg )
and its working as expected.

@sunrao sir kindly assign to respective tester to test the functionality testing.

**Comment by sunrao** [comment]
@IshantRevclerx You can check the functionality also, Tester will check during Main run

**Comment by IshantRevclerx** [comment]
@sunrao, I have checked the functionality and its working as expected.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have cheked above mention Security issue on production and its working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to confirm this point.

**Comment by prashantjadhav92** [comment]
Verified by the client.
