### ISSUE TITLE
SEC-4745 No brute force protection for current password on password change

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#69]
There is not brute force protection for current password on password change. As a result, XSS / leaked session might allow attacker to brute force current password, change it and take over the account.

Steps to Reproduce:
Login to partners.acronis.com
Go to user profile, https://partners.acronis.com/#user/profile/
Press Change Password button
Make multiple attempts to set incorrect password
Try to set correct password afterwards - see that it is accepted
Fix:
Implement brute force protection for current password in change password functionality
Proposed rate limits are 10 attempts per 15 minutes

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above mentioned Security Issue and currently there is not brute force protection for current password on password change available.

**Comment by shivmishra** [comment]
@IshantRevclerx i didnt get here, can we talk to understand the issue

**Comment by shivmishra** [comment]
fixed in this https://github.com/MindMatrix/AMP/pull/51821

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality also on the given branch ( ( https://pr-51821.dvl.amp.vg/) and its working as expected now.

**Comment by shivmishra** [comment]
@IshantRevclerx plz check this issue on this PR https://github.com/MindMatrix/AMP/pull/52021
as earlier PR doesn't get approved so fix here in new branch

**Comment by shivmishra** [comment]
check after build, should be fixed

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, The given branch is not working ( https://pr-52021.dvl.amp.vg/login ) 
On Chrome showing this error
![image](https://user-images.githubusercontent.com/92088937/188787458-e5ac29aa-12f9-443a-a6c3-48f521453d0e.png)

On Mozila showing this error
![image](https://user-images.githubusercontent.com/92088937/188787699-68366ce9-0480-4324-aa46-e56a6c380869.png)

**Comment by shivmishra** [comment]
updated from main so check after build

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao Sir, I have checked above security issue and basic functionality on the given branch  ( https://pr-52021.dvl.amp.vg/login ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, I have checked above security issue on Acronis production, If we entered incorrect current password on the change password modal,showing incorrect massage.
![image](https://user-images.githubusercontent.com/92088937/190125813-0d16bbcf-1696-429a-8ea1-76094b31b81e.png)

On Live, It's working as expected 

![image](https://user-images.githubusercontent.com/92088937/190125721-0ead9c0e-7432-438a-84b4-facfdfe87a71.png)

On Main, It's working as expected 

![image](https://user-images.githubusercontent.com/92088937/190125762-f1565b1d-0e23-489b-a76f-47c78d6cdbf9.png)

**Comment by shivmishra** [comment]
check again, there were column missing which is fixed now

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis Production and It's working as expected now.

**Comment by prashantjadhav92** [comment]
Verified by the client.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx as per the client this is not fixed yet. Can you please check this again?

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, curently if we user enters incorrect password for more than 11 times in the change password modal, he gets locked for 5 mins. If we user enters incorrect password again he gets an error massage. He can still enters the correct password to change his password.
Kindly letus know if client is expecting some different results.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx please check the initial request on this ticket.

In the fix the client has mentioned the fix as:

Implement brute force protection for current password in change password functionality
Proposed rate limits are 10 attempts per 15 minutes

**Comment by shivmishra** [comment]
@prashantjadhav92 @IshantRevclerx please check here 
https://github.com/MindMatrix/AMP/pull/52511

**Comment by IshantRevclerx** [comment]
@shivmishra Sir, @sunrao sir, I have checked above security issue and basic functionality on the given branch ( https://pr-52511.dvl.amp.vg/ ) and It's working as expected now.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
Asked the client to verify.

**Comment by prashantjadhav92** [comment]
Verified by the client.
