### ISSUE TITLE
SEC-4874 - XSS on /html/[template-id]/0/index.html page

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#99]
XSS is possible on /html/[template-id]/0/index.html page due to possibility to save custom JS code in POST request to /api/SavePage endoint

Steps to Reproduce
Open the url: https://partners.acronis.com/#communicate/email
Select "Compose"
Select template > Import > Import Design > Inject malicious javascript code, e.g. ><img src=x onerror=alert(document.domain>
Then access url https://partners.acronis.com/html/[template-id]/0/index.html (set proper [template-id] in the link) and see JavaScript code executed
Fix: it must not be possible to include custom JS. All untrusted input must be encoded

**Comment by IshantRevclerx** [comment]
@shaileshtayde Sir, I have checked above security issue and JS getting executed  when we Inject  javascript code in the import design input field. 

![image](https://user-images.githubusercontent.com/92088937/183893167-e3896c3e-7e72-4eff-8f4b-82836f5f7b2e.png)

**Comment by YogendraMatkar** [comment]
@IshantRevclerx, this issue is fixed now, u can test on https://pr-51609.dvl.amp.vg/

**Comment by IshantRevclerx** [comment]
@Vish-Patil Sir and @YogendraMatkar Sir, I have checked above security issue on the given branch ( https://pr-51609.dvl.amp.vg/), with the paylod mentioned in the attached text file and JS still getting executed.
[Payload.txt](https://github.com/MindMatrix/SecurityTracker/files/9381488/Payload.txt)

User Name : Security Ishant
Company Name : Automation Testers

![image](https://user-images.githubusercontent.com/92088937/185601611-3063b990-7ade-4678-af82-23828896fb11.png)

**Comment by YogendraMatkar** [comment]
@IshantRevclerx, this scenario is now handled, Also please test with script tag as in previous built we have restricted it.

eg : 
<br onkeypress="alert(1)" contenteditable>test</br>
<button onclick="alert("Hi")">Click</button>
**<script>alert("Virus!!!!!!")</script>**

**Comment by IshantRevclerx** [comment]
@Vish-Patil, @YogendraMatkar, @sunrao sir, I have checked above security issue and also I have checked basic functionality on the given branch ( https://pr-51609.dvl.amp.vg/ ) and its working as expected.

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue on Acronis production and its working as expected now.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx I have asked the client to verify this.

**Comment by prashantjadhav92** [comment]
Verified by the client.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx @sunrao @shaileshtayde, Acronis has reported this issue to be reproducible again. The issue was resolved back in September 2022.

Steps to reproduce:

* Open the url: https://partners.acronis.com/#communicate/email
* Open Developer Tools -> Network
* Select "Compose"
* Select template and press Next
* Press Save
* In Developer Tools find request to /SavePage and copy csrf token, JWT, pageid, emailid and templateid
* Make the following request (e.g. using Burp Suite, set proper <CSRF_TOKEN>, <JWT_TOKEN> and ids for pageid, emailid and templateid)
POST /api/SavePage HTTP/1.1
Host: partners.acronis.com
Cookie: X-CSRF-Token=<CSRF_TOKEN>; jwt=<JWT_TOKEN)
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=utf-8
X-Csrf-Token: <CSRF_TOKEN>
X-Requested-With: XMLHttpRequest
Content-Length: 2943
Origin: https://partners.acronis.com/
Dnt: 1
Referer: https://partners.acronis.com/v4u/design-editor.aspx?templateid=131611&isstepprocess=true&ishideimport=False&istestemail=False&emailid=39915
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
Te: trailers
Connection: close
 
{"pageid":119845,"mobilepage":0,"externalTemplateXML":"<ExternalTemplates></ExternalTemplates>","pagexml":"<page padding=\"\" bordercolor=\"#ffffff\" borderwidth=\"0px\" borderstyle=\"none\" totalwebnavigationtabs=\"0\" associatedto=\"0\" pageid=\"119845\" iswebnavinserted=\"0\" showinwebnav=\"false\" nextid=\"13\" objectmmid=\"0\" disconnected=\"False\" pagerotate=\"0\" backgroundimage=\"undefined\" backgroundcolor=\"#e9f3ff\" pagetitle=\"Blank%20Page%20637514728337556174\" printmargin=\"0\" height=\"1000\" width=\"640\" ispageoverflow=\"false\" islock=\"false\" noofpages=\"0\" masterpageid=\"0\" ismasterpage=\"0\" ischanged=\"1\" fitbgimage=\"false\"  pageanimation=\"\" isgotowebinar=\"false\" isemailpage=\"true\" sourceid=\"0\" pageduration=\"undefined\" backgroundvideo=\"undefined\" bgvideostarttime=\"0\" bgvideoduration=\"0\" islocksection=\"false\" ismapscenetobgvideo=\"false\" companyorgcolor=\"undefined\"><text id='objectCustomProperties' objecttype='text' objectmmid='10' width='612px' height='-1px' top='0px' left='0px' borderthickness='0px' bordercolor='#FFFFFF' borderstyle='0' backgroundcolor='' layername='TextObject Layer' lockforreference='0' islinked='0' zindex='103' visible='1' itemlinkid='0' itemlinkto='0' locksizeandposition='0' dbelementid='0' islocked='0' cssname='' objectflow='0' repeaterid='0' position='absolute' groupname='' behavior='' objectorder='10' autofit='0' autofitmin='6' autofitmax='48' autofitcurrentfontsize='' lockcontent='0' lockstyle='0' datafield='0' isrotate='0' rotvalue='0' iscustompointing='0' customwrap='0' mousepositionsx='' mousepositionsy='' offsetwidth='' offsetheight='' isemailobject='true'><content><![CDATA[<table contenteditable=\"false\" cellspacing=\"0\" cellpadding=\"0\">\n<img src onerror=alert(1)>]]></content><hdnContent><![CDATA[]]></hdnContent></text><behaviors></behaviors><metadatainformation><pagetitle><![CDATA[]]></pagetitle><metadescription><![CDATA[]]></metadescription><metakeywords><![CDATA[]]></metakeywords><metaimage><![CDATA[]]></metaimage><metakeywordsh1><![CDATA[]]></metakeywordsh1><metakeywordsh2><![CDATA[]]></metakeywordsh2><metakeywordsh3><![CDATA[]]></metakeywordsh3><googleanalytics><![CDATA[]]></googleanalytics><pagescript><![CDATA[]]></pagescript><googletrackingcode><![CDATA[]]></googletrackingcode></metadatainformation><datasources objectmmid=\"10\"></datasources>projectXML<projectsources></projectsources></page>","theme":"","emailAlign":"0","pgmgmtxml":"<rules></rules>","btnXml":"","subject":"A friendly reminder – hackers love holidays","makeemailreusable":false,"savepage":true,"reusablename":"","iswireframe":false, "islocksection":false,"shoinweb":false,"formidforpage":0,"emailid":39915,"isforapproval":false, "deletedobjectids":"","webAlign":"1","isEmailResponsive":false,"strplaceholderorder":"", "previewText":"","isInteractiveBanner":false,"uniquesign":0,"isGoToWebinar":false, "pauseAnimation":false,"templateid":131611}

* Then access url https://partners.acronis.com/html/[template-id]/0/index.html (set proper [template-id] in the link) and see JavaScript code executed

Example: https://partners.acronis.com/html/131611/0-1/index.html

Fix: it must not be possible to include custom JS. All untrusted input must be encoded

**Comment by prashantjadhav92** [comment]
@Vish-Patil please provide a status update on this item.

**Comment by prashantjadhav92** [comment]
@Vish-Patil @shaileshtayde can you share an update here?

**Comment by prashantjadhav92** [comment]
@Vish-Patil @shaileshtayde @IshantRevclerx what is the status of this security issue?

**Comment by Vish-Patil** [comment]
@prashantjadhav92 this will be resolved by setting strictasanitization to true.
pls discuss this with prod team.
